### ISSUE TITLE
`cargo cyclonedx` v0.4.0 release checklist

### ISSUE THREAD

**Issue by Shnatsel** [CycloneDX/cyclonedx-rust-cargo#521]
- [x] Resolve https://github.com/CycloneDX/cyclonedx-rust-cargo/issues/495
 - [x] Update README.md #543
 - [x] Write a changelog #540
 - [x] Release a non-semver-breaking version of `cyclonedx-bom`, some changes to it are prerequisites to `cargo cyclonedx` v0.4.0 #548
 - [x] Bump minimum required `cyclonedx-bom` version in `cargo cyclonedx`'s Cargo.toml 8d6a58f08db8b90aecbbde1f996693492c924161
 - [ ] Ship it

**Comment by Shnatsel** [comment]
v0.4.0 is now up on crates.io
