### ISSUE TITLE
Support spec version 1.5

### ISSUE THREAD

**Issue by justahero** [CycloneDX/cyclonedx-rust-cargo#646]
The Spec version 1.5 was released last year, therefore support [version 1.5](https://cyclonedx.org/docs/1.5/json) should be added. Initial work has begun in #584, it covers the first 4 items of the list below, but adding everything in a single PR is easily too much to review.

I checked the specification and collected the list of changes from [version 1.4](https://cyclonedx.org/docs/1.4/json) to [version 1.5](https://cyclonedx.org/docs/1.5/json). My hope is that the work can be split into separate PRs to provide better progress updates.

* [x] top level [`version`](https://cyclonedx.org/docs/1.5/json/#version) field not required anymore, see #584
* [x] add top level [`annotations`](https://cyclonedx.org/docs/1.5/json/#annotations), see #584
* [x] add [`trustZone`](https://cyclonedx.org/docs/1.5/json/#services_items_trustZone) to `Service`, see #584
* [x] add [`lifecycles`](https://cyclonedx.org/docs/1.5/json/#metadata_lifecycles) field to `Metadata`, see #584
* [x] expand [Component `type`](https://cyclonedx.org/docs/1.5/json/#metadata_component_type) in `Metadata` with new enum values, see #654
* [x] update [`tools`](https://cyclonedx.org/docs/1.5/json/#metadata_tools) in `Metadata`, changed to `oneOf`. see #656 
* [x] add `bom-ref` field (`refType`) to `OrganizationalContact`, e.g. in [`authors`](https://cyclonedx.org/docs/1.5/json/#metadata_authors) in `Metadata`, see #658 658
* [x] add [`modelCard`](https://cyclonedx.org/docs/1.5/json/#metadata_component_modelCard) & [`data`](https://cyclonedx.org/docs/1.5/json/#metadata_component_data) to `Component`, see #660 
* [x] `externalReference` type changed, see #663
  * [x] [`url`](https://cyclonedx.org/docs/1.5/json/#metadata_component_externalReferences_items_url) is a `oneOf` now
  * [x] [`type`](https://cyclonedx.org/docs/1.5/json/#metadata_component_externalReferences_items_type) got a lot more enum values
* [x] `licenseChoice` changed, either multiple licenses or a single spdx license expression, see commit in b8679b2da7e69e4d52df0cc21ca258656ef2d1f0
* [x] `tool` is marked as deprecated in `Tools`
* [x] `organizationalEntity` also got a `bom-ref`, same as `organizationalContact`, see #674 
* [x] `license` updated, see #692 
  * [x] add `bom-ref` field
  * [x] add `licensing` object with nested fields, e.g. `licensor`, `licensee`, `purchaser`, `licenseTypes`
* [x] [`data`](https://cyclonedx.org/docs/1.5/json/#services_items_data) field in `Service` changed to `serviceData` from `dataClassification` with a few more fields, see #673
* [x] [`evidence`](https://cyclonedx.org/docs/1.5/json/#components_items_evidence) in `Component` expands with more fields, e.g. `identity`, see #676
* [x] `Composition`
  * [x] receives `bom-ref`, see #678
  * [x] has new field [`vulnerabilities`](https://cyclonedx.org/docs/1.5/json/#compositions_items_vulnerabilities), see #678
  * [x] `assemblies` has now a `oneOf` relation, either `refLinkType` or `bomLinkElementType`
  * [x] [`aggregateType`](https://cyclonedx.org/docs/1.5/json/#compositions_items_aggregate) has a few more enum values, see #681
* [x] [`method`](https://cyclonedx.org/docs/1.5/json/#vulnerabilities_items_ratings_items_method) (`scoreMethod`) in `Rating` has new enum values, see #682
* [x] `vulnerability` has new fields, see #683
  * [x] [`workaround`](https://cyclonedx.org/docs/1.5/json/#vulnerabilities_items_workaround)
  * [x] [`proofOfConcept`](https://cyclonedx.org/docs/1.5/json/#vulnerabilities_items_proofOfConcept)
  * [x] [`rejected`](https://cyclonedx.org/docs/1.5/json/#vulnerabilities_items_rejected)
  * [x] `tools` changed
  * [x] `analysis` has new fields, `firstIssued`, `lastUpdated`
* [x] `refType` is split into `refLinkType` & `bomLinkElementType`
* [x] top level [`formulation`](https://cyclonedx.org/docs/1.5/json/#formulation) including whole new set of types! #689
* [x] top level [`properties`](https://cyclonedx.org/docs/1.5/json/#properties), see #675

**Comment by pvdrz** [comment]
`formulation` was added in https://github.com/CycloneDX/cyclonedx-rust-cargo/pull/689

**Comment by felipesere** [comment]
Is `refType` the last missing item?

**Comment by justahero** [comment]
I will check off the item. Basically `refLinkType` & `bomLinkElementType` are both String types, where the latter one matches a specific pattern (see [`bomLinkElementType`](https://github.com/CycloneDX/specification/blob/master/schema/bom-1.5.schema.json#L141) definition vs [`refType`](https://github.com/CycloneDX/specification/blob/master/schema/bom-1.5.schema.json#L123)).

**Comment by Shnatsel** [comment]
This is implemented in latest git, and we're going to ship a release with this soon. Closing.

If you find something that is missing, please let us know by opening an issue!
